//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Nachnem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Докум поставки.
    /// </summary>
    // *** Start programmer edit section *** (ДокумПоставки CustomAttributes)

    // *** End programmer edit section *** (ДокумПоставки CustomAttributes)
    [AutoAltered()]
    [Caption("Документ поставки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокумПоставкиE", new string[] {
            "Дата as \'Дата\'",
            "НомерДокПост as \'Номер документа поставки\'",
            "Клиенты as \'Заказчик\'",
            "Клиенты.Заказчик as \'Заказчик\'",
            "Клиенты.АдресПоставки as \'Адрес поставки\'",
            "Клиенты.Телефон as \'Телефон\'",
            "Организация as \'Наименование организации\'",
            "Организация.НаимОрганиз"}, Hidden=new string[] {
            "Клиенты.Заказчик",
            "Организация.НаимОрганиз"})]
    [AssociatedDetailViewAttribute("ДокумПоставкиE", "ИнфОЗаказе", "ИнфОЗаказеE", true, "", "Информация о заказе", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ДокумПоставкиE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Заказчик")]
    [MasterViewDefineAttribute("ДокумПоставкиE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаимОрганиз")]
    [View("ДокумПоставкиL", new string[] {
            "Дата as \'Дата\'",
            "НомерДокПост as \'Номер документа поставки\'",
            "Организация.НаимОрганиз as \'Наименование организации\'",
            "Клиенты.Заказчик as \'Заказчик\'"})]
    public class ДокумПоставки : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомерДокПост;
        
        private IIS.Nachnem.Клиенты fКлиенты;
        
        private IIS.Nachnem.Организация fОрганизация;
        
        private IIS.Nachnem.DetailArrayOfИнфОЗаказе fИнфОЗаказе;
        
        // *** Start programmer edit section *** (ДокумПоставки CustomMembers)

        // *** End programmer edit section *** (ДокумПоставки CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.Дата CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.Дата Get start)

                // *** End programmer edit section *** (ДокумПоставки.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ДокумПоставки.Дата Get end)

                // *** End programmer edit section *** (ДокумПоставки.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.Дата Set start)

                // *** End programmer edit section *** (ДокумПоставки.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ДокумПоставки.Дата Set end)

                // *** End programmer edit section *** (ДокумПоставки.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерДокПост.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.НомерДокПост CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.НомерДокПост CustomAttributes)
        public virtual int НомерДокПост
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.НомерДокПост Get start)

                // *** End programmer edit section *** (ДокумПоставки.НомерДокПост Get start)
                int result = this.fНомерДокПост;
                // *** Start programmer edit section *** (ДокумПоставки.НомерДокПост Get end)

                // *** End programmer edit section *** (ДокумПоставки.НомерДокПост Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.НомерДокПост Set start)

                // *** End programmer edit section *** (ДокумПоставки.НомерДокПост Set start)
                this.fНомерДокПост = value;
                // *** Start programmer edit section *** (ДокумПоставки.НомерДокПост Set end)

                // *** End programmer edit section *** (ДокумПоставки.НомерДокПост Set end)
            }
        }
        
        /// <summary>
        /// Докум поставки.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Nachnem.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.Клиенты Get start)

                // *** End programmer edit section *** (ДокумПоставки.Клиенты Get start)
                IIS.Nachnem.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ДокумПоставки.Клиенты Get end)

                // *** End programmer edit section *** (ДокумПоставки.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.Клиенты Set start)

                // *** End programmer edit section *** (ДокумПоставки.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ДокумПоставки.Клиенты Set end)

                // *** End programmer edit section *** (ДокумПоставки.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Докум поставки.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.Организация CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Nachnem.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.Организация Get start)

                // *** End programmer edit section *** (ДокумПоставки.Организация Get start)
                IIS.Nachnem.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ДокумПоставки.Организация Get end)

                // *** End programmer edit section *** (ДокумПоставки.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.Организация Set start)

                // *** End programmer edit section *** (ДокумПоставки.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ДокумПоставки.Организация Set end)

                // *** End programmer edit section *** (ДокумПоставки.Организация Set end)
            }
        }
        
        /// <summary>
        /// Докум поставки.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе CustomAttributes)
        public virtual IIS.Nachnem.DetailArrayOfИнфОЗаказе ИнфОЗаказе
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе Get start)

                // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе Get start)
                if ((this.fИнфОЗаказе == null))
                {
                    this.fИнфОЗаказе = new IIS.Nachnem.DetailArrayOfИнфОЗаказе(this);
                }
                IIS.Nachnem.DetailArrayOfИнфОЗаказе result = this.fИнфОЗаказе;
                // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе Get end)

                // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе Set start)

                // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе Set start)
                this.fИнфОЗаказе = value;
                // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе Set end)

                // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокумПоставкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумПоставкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумПоставкиE", typeof(IIS.Nachnem.ДокумПоставки));
                }
            }
            
            /// <summary>
            /// "ДокумПоставкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумПоставкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумПоставкиL", typeof(IIS.Nachnem.ДокумПоставки));
                }
            }
        }
    }
}
